services:
  - type: web
    name: flask-app
    runtime: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn db:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db-name
          property: connectionString